# Some aspects/uniques have their variable number as second (number_idx_1) or third (number_idx_2)
ASPECT_NUMBER_AT_IDX1 = [
    # Legendary
    "frostbitten_aspect",
    "frostbitten_aspect",
    "aspect_of_artful_initiative",
    "aspect_of_artful_initiative",
    "aspect_of_noxious_ice",
    "aspect_of_noxious_ice",
    "elementalists_aspect",
    "elementalists_aspect",
    "snowveiled_aspect",
    "snowveiled_aspect",
    "aspect_of_might",
    "aspect_of_might",
    "assimilation_aspect",
    "assimilation_aspect",
    "exploiters_aspect",
    "exploiters_aspect",
    "aspect_of_audacity",
    "aspect_of_audacity",
    "ghostwalker_aspect",
    "ghostwalker_aspect",
    "aspect_of_slaughter",
    "aspect_of_slaughter",
    "aspect_of_tempering_blows",
    "aspect_of_tempering_blows",
    "aspect_of_ancestral_charge",
    "aspect_of_ancestral_charge",
    "aspect_of_encroaching_wrath",
    "aspect_of_encroaching_wrath",
    "brawlers_aspect",
    "brawlers_aspect",
    "devilish_aspect",
    "devilish_aspect",
    "earthstrikers_aspect",
    "earthstrikers_aspect",
    "steadfast_berserkers_aspect",
    "steadfast_berserkers_aspect",
    "windlasher_aspect",
    "windlasher_aspect",
    "bear_clan_berserkers_aspect",
    "bear_clan_berserkers_aspect",
    "aspect_of_mending_stone",
    "aspect_of_mending_stone",
    "aspect_of_metamorphic_stone",
    "aspect_of_metamorphic_stone",
    "aspect_of_the_stampede",
    "aspect_of_the_stampede",
    "aspect_of_the_trampled_earth",
    "aspect_of_the_trampled_earth",
    "lightning_dancers_aspect",
    "lightning_dancers_aspect",
    "raw_might_aspect",
    "raw_might_aspect",
    "aspect_of_decay",
    "aspect_of_decay",
    "osseous_gale_aspect",
    "osseous_gale_aspect",
    "rotting_aspect",
    "rotting_aspect",
    "aspect_of_exposed_flesh",
    "aspect_of_exposed_flesh",
    "coldbringers_aspect",
    "coldbringers_aspect",
    "aspect_of_uncanny_treachery",
    "aspect_of_uncanny_treachery",
    "aspect_of_lethal_dusk",
    "aspect_of_lethal_dusk",
    "enshrouding_aspect",
    "enshrouding_aspect",
    "aspect_of_arrow_storms",
    "aspect_of_arrow_storms",
    "aspect_of_bursting_venoms",
    "aspect_of_bursting_venoms",
    "aspect_of_pestilent_points",
    "aspect_of_pestilent_points",
    "aspect_of_synergy",
    "aspect_of_synergy",
    "icy_alchemists_aspect",
    "icy_alchemists_aspect",
    "toxic_alchemists_aspect",
    "toxic_alchemists_aspect",
    "trickshot_aspect",
    "trickshot_aspect",
    "snowguards_aspect",
    "snowguards_aspect",
    "aspect_of_frozen_orbit",
    "aspect_of_frozen_orbit",
    "serpentine_aspect",
    "serpentine_aspect",
    # Unique
    "banished_lords_talisman",
    "ancients_oath",
    "battle_trance",
    "gohrs_devastating_grips",
    "waxing_gibbous",
    "black_river",
    "bloodless_scream",
    "ring_of_mendeln",
    "blue_rose",
    "esadoras_overflowing_cameo",
    "staff_of_endless_rage",
    "fists_of_fate",
    "mothers_embrace",
    "temerity",
    "the_butchers_cleaver",
    "xfals_corroded_signet",
    "writhing_band_of_trickery",
    "airidahs_inexorable_will",
]

ASPECT_NUMBER_AT_IDX2 = [
    # Legendary
    "aspect_of_retribution",
    "aspect_of_retribution",
    "aspect_of_serration",
    "aspect_of_serration",
    "aspect_of_untimely_death",
    "aspect_of_untimely_death",
    # Unique
    "azurewrath",
    "soulbrand",
    "ring_of_red_furor",
]

ERROR_MAP = {
    "thoms": "thorns",
    "seythe": "scythe",
    "@arbarian": "(barbarian",
    "mruid": "(druid",
    "omuid": "(druid",
    "gorcerer": "sorcerer",
    "garbarian": "barbarian",
    "two-handed!": "two-handed",
    "two-handed.": "two-handed",
    "(arbarian": "barbarian",
}
